module.exports = {
  timezones: [
    { name: "Pacific/Midway", value: "(UTC-11) Pacific/Midway" },
    { name: "America/Adak", value: "(UTC-10/UTC-09) America/Adak" },
    { name: "Pacific/Honolulu", value: "(UTC-10) Pacific/Honolulu" },
    { name: "Pacific/Marquesas", value: "(UTC-09:30) Pacific/Marquesas" },
    { name: "America/Anchorage", value: "(UTC-09/UTC-08) America/Anchorage" },
    { name: "Pacific/Gambier", value: "(UTC-09) Pacific/Gambier" },
    {
      name: "America/Los_Angeles",
      value: "(UTC-08/UTC-07) America/Los Angeles",
    },
    { name: "Pacific/Pitcairn", value: "(UTC-08) Pacific/Pitcairn" },
    {
      name: "America/Yellowknife",
      value: "(UTC-07/UTC-06) America/Yellowknife",
    },
    { name: "America/Ojinaga", value: "(UTC-07/UTC-06) America/Ojinaga" },
    { name: "America/Mazatlan", value: "(UTC-07/UTC-06) America/Mazatlan" },
    { name: "America/Inuvik", value: "(UTC-07/UTC-06) America/Inuvik" },
    { name: "America/Edmonton", value: "(UTC-07/UTC-06) America/Edmonton" },
    { name: "America/Denver", value: "(UTC-07/UTC-06) America/Denver" },
    { name: "America/Chihuahua", value: "(UTC-07/UTC-06) America/Chihuahua" },
    {
      name: "America/Cambridge_Bay",
      value: "(UTC-07/UTC-06) America/Cambridge Bay",
    },
    { name: "America/Phoenix", value: "(UTC-07) America/Phoenix" },
    { name: "Pacific/Easter", value: "(UTC-06/UTC-05) Pacific/Easter" },
    {
      name: "America/Mexico_City",
      value: "(UTC-06/UTC-05) America/Mexico City",
    },
    { name: "America/Chicago", value: "(UTC-06/UTC-05) America/Chicago" },
    { name: "Pacific/Galapagos", value: "(UTC-06) Pacific/Galapagos" },
    { name: "America/Costa_Rica", value: "(UTC-06) America/Costa Rica" },
    { name: "America/New_York", value: "(UTC-05/UTC-04) America/New York" },
    { name: "America/Montreal", value: "(UTC-05/UTC-04) America/Montreal" },
    { name: "America/Bogota", value: "(UTC-05) America/Bogota" },
    { name: "America/Caracas", value: "(UTC-04:30) America/Caracas" },
    { name: "Atlantic/Bermuda", value: "(UTC-04/UTC-03) Atlantic/Bermuda" },
    { name: "Antarctica/Palmer", value: "(UTC-04/UTC-03) Antarctica/Palmer" },
    { name: "America/Santiago", value: "(UTC-04/UTC-03) America/Santiago" },
    { name: "America/Cuiaba", value: "(UTC-04/UTC-03) America/Cuiaba" },
    { name: "America/Manaus", value: "(UTC-04) America/Manaus" },
    { name: "America/La_Paz", value: "(UTC-04) America/La Paz" },
    {
      name: "America/St_Johns",
      value: "(UTC-03:30/UTC-02:30) America/St Johns",
    },
    { name: "America/Sao_Paulo", value: "(UTC-03/UTC-02) America/Sao Paulo" },
    {
      name: "America,{name: /Argentina/Buenos_Aires",
      value: "(UTC-03/UTC-02) America/Argentina/Buenos Aires",
    },
    { name: "Atlantic/Stanley", value: "(UTC-03) Atlantic/Stanley" },
    { name: "Antarctica/Rothera", value: "(UTC-03) Antarctica/Rothera" },
    { name: "America/Fortaleza", value: "(UTC-03) America/Fortaleza" },
    {
      name: "America,{name: /Argentina/Salta",
      value: "(UTC-03) America/Argentina/Salta",
    },
    {
      name: "Atlantic/South_Georgia",
      value: "(UTC-02) Atlantic/South Georgia",
    },
    { name: "America/Noronha", value: "(UTC-02) America/Noronha" },
    { name: "Atlantic/Azores", value: "(UTC-01/UTC+00) Atlantic/Azores" },
    { name: "Atlantic/Cape_Verde", value: "(UTC-01) Atlantic/Cape Verde" },
    { name: "Africa/Abidjan", value: "(UTC+00) Africa/Abidjan" },
    { name: "Africa/Casablanca", value: "(UTC+00) Africa/Casablanca" },
    { name: "Africa/El_Aaiun", value: "(UTC+00) Africa/El Aaiun" },
    { name: "Africa/Ouagadougou", value: "(UTC+00) Africa/Ouagadougou" },
    { name: "America/Danmarkshavn", value: "(UTC+00) America/Danmarkshavn" },
    { name: "Antarctica/Vostok", value: "(UTC+00) Antarctica/Vostok" },
    { name: "Atlantic/Reykjavik", value: "(UTC+00) Atlantic/Reykjavik" },
    { name: "Atlantic/Canary", value: "(UTC+00/UTC+01) Atlantic/Canary" },
    { name: "Europe/London", value: "(UTC+00/UTC+01) Europe/London" },
    { name: "Africa,{name: /Porto-Novo", value: "(UTC+01) Africa/Porto-Novo" },
    { name: "Africa/Tunis", value: "(UTC+01/UTC+02) Africa/Tunis" },
    {
      name: "Arctic/Longyearbyen",
      value: "(UTC+01/UTC+02) Arctic/Longyearbyen",
    },
    { name: "Europe/Paris", value: "(UTC+01/UTC+02) Europe/Paris" },
    { name: "Africa/Cairo", value: "(UTC+02) Africa/Cairo" },
    { name: "Asia/Jerusalem", value: "(UTC+02/UTC+03) Asia/Jerusalem" },
    { name: "Europe/Bucharest", value: "(UTC+02/UTC+03) Europe/Bucharest" },
    { name: "Africa/Nairobi", value: "(UTC+03) Africa/Nairobi" },
    { name: "Antarctica/Syowa", value: "(UTC+03) Antarctica/Syowa" },
    { name: "Asia/Baghdad", value: "(UTC+03) Asia/Baghdad" },
    { name: "Europe/Kaliningrad", value: "(UTC+03) Europe/Kaliningrad" },
    { name: "Indian/Comoro", value: "(UTC+03) Indian/Comoro" },
    { name: "Asia/Tehran", value: "(UTC+03:30/UTC+04:30) Asia/Tehran" },
    { name: "Asia/Dubai", value: "(UTC+04) Asia/Dubai" },
    { name: "Europe/Moscow", value: "(UTC+04) Europe/Moscow" },
    { name: "Indian/Mauritius", value: "(UTC+04) Indian/Mauritius" },
    { name: "Asia/Yerevan", value: "(UTC+04/UTC+05) Asia/Yerevan" },
    { name: "Asia/Kabul", value: "(UTC+04:30) Asia/Kabul" },
    { name: "Asia/Karachi", value: "(UTC+05) Asia/Karachi" },
    { name: "Indian/Maldives", value: "(UTC+05) Indian/Maldives" },
    { name: "Asia/Kolkata", value: "(UTC+05:30) Asia/Kolkata" },
    { name: "Asia/Katmandu", value: "(UTC+05:45) Asia/Kathmandu" },
    { name: "Antarctica/Mawson", value: "(UTC+06) Antarctica/Mawson" },
    { name: "Asia/Dhaka", value: "(UTC+06) Asia/Dhaka" },
    { name: "Indian/Chagos", value: "(UTC+06) Indian/Chagos" },
    { name: "Asia/Rangoon", value: "(UTC+06:30) Asia/Rangoon" },
    { name: "Indian/Cocos", value: "(UTC+06:30) Indian/Cocos" },
    { name: "Antarctica/Davis", value: "(UTC+07) Antarctica/Davis" },
    { name: "Asia/Bangkok", value: "(UTC+07) Asia/Bangkok" },
    { name: "Indian/Christmas", value: "(UTC+07) Indian/Christmas" },
    { name: "Antarctica/Casey", value: "(UTC+08) Antarctica/Casey" },
    { name: "Asia/Singapore", value: "(UTC+08) Asia/Singapore" },
    { name: "Australia/Perth", value: "(UTC+08) Australia/Perth" },
    { name: "Australia/Eucla", value: "(UTC+08:45/UTC+09:45) Australia/Eucla" },
    { name: "Asia/Tokyo", value: "(UTC+09) Asia/Tokyo" },
    { name: "Pacific/Palau", value: "(UTC+09) Pacific/Palau" },
    { name: "Australia/Darwin", value: "(UTC+09:30) Australia/Darwin" },
    {
      name: "Australia/Adelaide",
      value: "(UTC+09:30/UTC+10:30) Australia/Adelaide",
    },
    {
      name: "Antarctica/DumontDUrville",
      value: "(UTC+10) Antarctica/DumontDUrville",
    },
    { name: "Asia/Yakutsk", value: "(UTC+10) Asia/Yakutsk" },
    { name: "Australia/Brisbane", value: "(UTC+10) Australia/Brisbane" },
    { name: "Pacific/Guam", value: "(UTC+10) Pacific/Guam" },
    { name: "Australia/Sydney", value: "(UTC+10/UTC+11) Australia/Sydney" },
    {
      name: "Australia/Lord_Howe",
      value: "(UTC+10:30/UTC+11) Australia/Lord Howe",
    },
    { name: "Asia/Vladivostok", value: "(UTC+11) Asia/Vladivostok" },
    { name: "Pacific/Noumea", value: "(UTC+11) Pacific/Noumea" },
    { name: "Pacific/Norfolk", value: "(UTC+11:30) Pacific/Norfolk" },
    { name: "Asia/Magadan", value: "(UTC+12) Asia/Magadan" },
    { name: "Pacific/Funafuti", value: "(UTC+12) Pacific/Funafuti" },
    {
      name: "Antarctica/South_Pole",
      value: "(UTC+12/UTC+13) Antarctica/South Pole",
    },
    { name: "Pacific/Auckland", value: "(UTC+12/UTC+13) Pacific/Auckland" },
    { name: "Pacific/Fiji", value: "(UTC+12/UTC+13) Pacific/Fiji" },
    { name: "Pacific/Chatham", value: "(UTC+12:45/UTC+13:45) Pacific/Chatham" },
    { name: "Pacific/Enderbury", value: "(UTC+13) Pacific/Enderbury" },
    { name: "Pacific/Apia", value: "(UTC+13/UTC+14) Pacific/Apia" },
    { name: "Pacific/Kiritimati", value: "(UTC+14) Pacific/Kiritimati" },
  ],
  specialisations: [
    { name: "Acupuncture", value: "Acupuncture" },
    { name: "Allergist/Immunologist", value: "Allergy/Immunology" },
    { name: "Anesthesiologist", value: "Anesthesiology" },
    { name: "Audiologist", value: "Audiologist" },
    { name: "Ayurveda", value: "Ayurveda" },
    { name: "Cardiac Electrophysiologist", value: "Cardiac Electrophysiology" },
    { name: "Cardiologist", value: "Cardiology" },
    { name: "Cardiothoracic Surgeon", value: "Cardiothoracic Surgeon" },
    { name: "Colorectal Surgeon", value: "Colorectal Surgeon" },
    { name: "Cosmetic Surgeon", value: "Cosmetic Surgeon" },
    { name: "Dentist", value: "Dentistry" },
    { name: "Dermatologist", value: "Dermatology" },
    { name: "Developmental Pediatrician", value: "Developmental Pediatrics" },
    { name: "Diabetologist", value: "Diabetology" },
    { name: "Ear-Nose-Throat Specialist (ENT)", value: "Ear-Nose-Throat(ENT)" },
    { name: "Embryologist", value: "Embryology  Services" },
    {
      name: "Emergency Medicine Physician",
      value: "Emergency Medicine Clinic",
    },
    { name: "Endocrinologist", value: "Endocrinology" },
    { name: "Endodontist", value: "Endodontist" },
    { name: "Epidemiologist", value: "Epidemiology" },
    { name: "Family Practitioner", value: "Family Practitioner" },
    { name: "Fitness Center", value: "Fitness Center" },
    { name: "Gastroenterologist", value: "Gastroenterology" },
    { name: "General Physician", value: "General Medicine" },
    { name: "General Surgeon", value: "General Surgery" },
    { name: "Geneticist", value: "Geneticis" },
    { name: "Gym", value: "Gym" },
    { name: "Hand Surgeon", value: "Hand Surgery" },
    { name: "Hematologist", value: "Hematology" },
    { name: "Homeopathy", value: "Homeopathy" },
    { name: "Infectious Disease Specialist", value: "Infectious Disease" },
    { name: "Infertility Clinic", value: "Infertility Clinic" },
    { name: "Integrated Medicine", value: "Integrated Medicine" },
    { name: "Internist", value: "Internist" },
    { name: "Laboratory Medicine Specialist", value: "Laboratory Medicine" },
    { name: "Nephrologist", value: "Nephrology" },
    { name: "Neurologist", value: "Neurology" },
    { name: "Neurosurgeon", value: "Neurosurgery" },
    { name: "Nuclear Medicine Specialist", value: "Nuclear Medicine" },
    { name: "Nutritionist", value: "Nutrition" },
    { name: "Obstetrician/Gynecologist", value: "Obstetrics/Gynaecology" },
    { name: "Occupational Therapist", value: "Occupational Therapy" },
    { name: "Oncologist", value: "Oncology" },
    { name: "Ophthalmologist", value: "Ophthalmology" },
    { name: "Oral Surgeon", value: "Oral Surgery" },
    { name: "Orthodontist", value: "Orthodontics" },
    { name: "Orthopedic Surgeon", value: "Orthopedic Surgery" },
    { name: "Pain Management Specialist", value: "Pain Management" },
    { name: "Pathologist", value: "Pathology" },
    { name: "Pediatric Dentist", value: "Pediatric Dentistry" },
    { name: "Pediatric Surgery", value: "Pediatric Surgeon" },
    { name: "Pediatrician", value: "Pediatrics" },
    { name: "Periodontist", value: "Periodontistry" },
    {
      name: "Physical Medicine and Rehab Specialist",
      value: "Physical Medicine and Rehab",
    },
    { name: "Physical Therapist", value: "Physical Therapy" },
    { name: "Physiotherapist", value: "Physiotherapist" },
    { name: "Plastic Surgeon", value: "Plastic Surgery" },
    { name: "Podiatrist", value: "Podiatry" },
    { name: "Polyclinic", value: "Polyclinic" },
    { name: "Pranic Healing", value: "Pranic Healing" },
    { name: "Primary Care Doctor", value: "Primary Care" },
    { name: "Prosthodontist", value: "Prosthodontistry" },
    { name: "Psychiatrist", value: "Psychiatry" },
    { name: "Psychologist", value: "Psychology" },
    { name: "Public Health Professional", value: "Public Health" },
    { name: "Pulmonologist", value: "Pulmonology" },
    { name: "Radiation Oncologist", value: "Radiation Oncology" },
    { name: "Radiologist", value: "Radiology" },
    { name: "Rheumatologist", value: "Rheumatology" },
    { name: "Sexual Medicine/Sexology", value: "Sexual Medicine/Sexology" },
    { name: "Siddha", value: "Siddha" },
    { name: "Sleep Disorders", value: "Sleep Disorders" },
    { name: "Spa and Saloon", value: "Spa and Saloon" },
    { name: "Speech Therapist", value: "Speech Therapist" },
    { name: "Sports Medicine", value: "Sports Medicine Specialist" },
    { name: "Trichology", value: "Trichology" },
    { name: "Urologist", value: "Urology" },
    { name: "Vascular Surgeon", value: "Vascular Surgery" },
    { name: "Veterinary Physician", value: "Veterinary" },
    { name: "Wellness Centre", value: "Wellness Centre" },
    { name: "Yoga", value: "Yoga" },
    { name: "Yoga Therapy", value: "Yoga Therapy" },
  ],
  fourspecialisations: [
    { name: "Acupuncture", value: "Acupuncture" },
    { name: "Allergist/Immunologist", value: "Allergy/Immunology" },
    { name: "Anesthesiologist", value: "Anesthesiology" },
    { name: "Audiologist", value: "Audiologist" },
  ],
};
